### ISSUE TITLE
Root GAR checklist

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#61]
- *Initial task list*
- [x] Create Your Passcode
- [x] Enter passcode
- *Post unlock task list*
- [x] Intro to Your Role
- [x] Incept Local GLEIF Single-Sig AID
- *Post incept task list*
- [x] Lead GLEIF External Multi-Sig AID Inception
- [x] Join GLEIF External Multi-Sig AID Inception
- *Multi-Sig task list*:
- [x] Initiate Manual Key Rotation
- [x] Join Manual Key Rotation
- [ ] Initiate Delegation Approval
  - [ ] One Way OOBI/Challenge with GARs
    - [ ] \*\* Wait for Delegation Request \*\* (notification)
  - [ ] Approve Delegation
- [ ] Join Delegation Approval
  - [ ] \*\* Wait for Join Delegation Request \*\* (notification)
  - [ ] Approve Delegation
- [ ] View Multi-Sig Event Logs
- *Single-Sig task list* :
- [ ] Perform Manual Key Rotation
