### ISSUE TITLE
External GAR checklist

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#62]
- *Initial task list*
- [x] Create Your Passcode
- [x] Enter passcode
- *Post unlock task list*
- [x] Intro to Your Role
- [x] Incept Local GLEIF Single-Sig AID
- *Post incept task list*
- Join One Way OOBI/Challenge with Lead Root GAR 
- [ ] (screen that says you need wait for notification (up arrow))
- Lead GLEIF External Multi-Sig AID Inception
- [ ] Select Well Known AID of Root AID
- Join GLEIF External Multi-Sig AID Inception
- *Multi-Sig task list*:
- [ ] Initiate Manual Key Rotation
- [ ] Join Manual Key Rotation
- [ ] Initiate ECR Credential Issuance
- [ ] Join ECR Credential Issuance
- [ ] Initiate ECR Credential Revocation
- [ ] Join ECR Credential Revocation
- [ ] View Multi-Sig Event Logs
- *Single-Sig task list* :
- [ ] Perform Manual Key Rotation
