### ISSUE TITLE
Internal GAR checklist

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#63]
- *Initial task list*
- [ ] Create Your Passcode
- [ ] Enter passcode
- *Post unlock task list*
- [ ] Intro to Your Role
- [ ] Incept Local GLEIF Single-Sig AID
- *Post incept task list*
- [ ] Join One Way OOBI/Challenge with Lead Root GAR 
  - [ ] (screen that says you need wait for notification (up arrow))
- [ ] Lead GLEIF Internal Multi-Sig AID Inception
  - [ ] Select Well Known AID of Root AID
- [ ] Join GLEIF Internal Multi-Sig AID Inception
- *Multi-Sig task list :*
- [ ] Initiate Manual Key Rotation
- [ ] Join Manual Key Rotation
- [ ] Initiate Credential Issuance
- [ ] Join Credential Issuance
- [ ] Initiate Credential Revocation
- [ ] Join Credential Revocation
- [ ] View Multi-Sig Event Logs
- [ ] Accept Credential
  - [ ] From notification
- *Single-Sig task list* :
- [ ] Perform Manual Key Rotation
