### ISSUE TITLE
QAR checklist

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#64]
- *Initial task list*
- [ ] Create Your Passcode
- [ ] Enter passcode
- *Post unlock task list*
- [ ] Intro to Your Role
- [ ] Incept Local QAR Single-Sig AID
- *Post incept task list*
- [ ] Join One Way OOBI/Challenge with Lead External GAR 
  - [ ] (screen that says you need wait for notification (up arrow))
- [ ] Lead QAR Multi-Sig AID Inception
  - [ ] Select Well Known AID of External AID
- [ ] Join QAR Multi-Sig AID Inception
- *Multi-Sig task list :*
- [ ] Initiate Manual Key Rotation
- [ ] Join Manual Key Rotation
- [ ] Initiate Credential Issuance
- [ ] Join Credential Issuance
- [ ] Initiate Credential Revocation
- [ ] Join Credential Revocation
- [ ] View Multi-Sig Event Logs
- [ ] Accept Credential
  - [ ] From notification
- *Single-Sig task list*:
- [ ] Perform Manual Key Rotation
