### ISSUE TITLE
LAR checklist

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keep#65]
- *Initial task list*
- [ ] Create Your Passcode
- [ ] Enter passcode
- *Post unlock task list*
- [ ] Intro to Your Role
- [ ] Understanding Single-Sig or Multi-Sig for Your Legal Entity
- [ ] Incept Local LAR Single-Sig AID
- *Multi-Sig task list:*
- [ ] Join One Way OOBI/Challenge with QAR 
  - [ ] (screen that says you need wait for notification (up arrow))
- [ ] Lead QAR Multi-Sig AID Inception
  - [ ] Select Well Known AID of QAR AID
- [ ] Join LAR Multi-Sig AID Inception
- [ ] Accept Credential
  - [ ] From notification
- [ ] *Multi-Sig task list (yes, we know it’s nested (it’s complicated)):*
  - [ ] Initiate Manual Key Rotation
  - [ ] Join Manual Key Rotation
  - [ ] Initiate Credential Issuance
  - [ ] Join Credential Issuance
  - [ ] Initiate Credential Revocation
  - [ ] Join Credential Revocation
  - [ ] View Multi-Sig Event Logs
- [ ] *Single-Sig task list*:
  - [ ] Perform Manual Key Rotation
- *Single-Sig task list:*
- [ ] Join One Way OOBI/Challenge with QAR 
  - [ ] (screen that says you need wait for notification (up arrow))
- [ ] Accept Credential
  - [ ] From notification
- [ ] Perform Manual Key Rotation
- [ ] Convert to Multi-Sig (post pilot)
